services:
  database:
    container_name: sdg-database
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"

  couchDb:
    container_name: couch
    image: "couchdb:latest"
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: "admin"
      COUCHDB_PASSWORD: "password"
    volumes:
      - ./couchdb_data:/opt/couchdb/data
      - ./couchdb_config:/opt/couchdb/etc/local.d
      - ./couchdb_log:/opt/couchdb/var/log

  couchdb-init:
    image: curlimages/curl:latest
    depends_on:
      couchDb:
        condition: service_started
    environment:
      COUCHDB_USER: "admin"
      COUCHDB_PASSWORD: "password"
      COUCHDB_DB: "model_results"
    entrypoint: >
      sh -c "
        echo 'Waiting for CouchDB to be ready...';
        until curl -s http://$${COUCHDB_USER}:$${COUCHDB_PASSWORD}@couch:5984/_all_dbs; do sleep 5; done;
        echo 'CouchDB is ready. Running initialization scripts...';
        curl -X PUT http://$${COUCHDB_USER}:$${COUCHDB_PASSWORD}@couch:5984/_users;
        curl -X PUT http://$${COUCHDB_USER}:$${COUCHDB_PASSWORD}@couch:5984/_replicator;
        curl -X PUT http://$${COUCHDB_USER}:$${COUCHDB_PASSWORD}@couch:5984/_global_changes;
        curl -X PUT http://$${COUCHDB_USER}:$${COUCHDB_PASSWORD}@couch:5984/$${COUCHDB_DB};
        curl -X PUT http://$${COUCHDB_USER}:$${COUCHDB_PASSWORD}@couch:5984/$${COUCHDB_DB}/_security -d '{ \
          \"admins\": { \"names\": [], \"roles\": [\"_admin\"] },
          \"members\": { \"names\": [], \"roles\": [] }
        }'
        curl -X PUT http://$${COUCHDB_USER}:$${COUCHDB_PASSWORD}@couch:5984/_node/nonode@nohost/_config/chttpd/enable_cors -d '\"true\"'
        curl -X PUT http://$${COUCHDB_USER}:$${COUCHDB_PASSWORD}@couch:5984/_node/nonode@nohost/_config/cors/origins -d '\"*\"'
      "

  sdg-middleware:
    container_name: sdg-middleware
    depends_on:
      - database
    image: ghcr.io/engineering-research-and-development/synthetic_data_generator_middleware:latest
    ports:
      - "8001:8001"
    environment:
      POSTGRES_HOST: "database"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
      GENERATOR_URL: "http://generator:8010"
      ALLOWED_ORIGINS: '*'

  generator:
    container_name: sdg-generator
    depends_on:
      - sdg-middleware
      - couchDb
    image: ghcr.io/engineering-research-and-development/synthetic_data_generator_server:latest
    environment:
      COUCHDB_USER: "admin"
      COUCHDB_PASSWORD: "password"
      COUCHDB_DB: "model_results"
      COUCHDB_HOST: "couch"
      MIDDLEWARE_URL: "http://sdg-middleware:8001/"
    ports:
      - "8010:8010"

  frontend:
    container_name: sdg-frontend
    image: ghcr.io/engineering-research-and-development/synthetic_data_generator_frontend:v0.0.5
    ports:
      - "5173:3000"
