services:

  database:
    container_name: sdg-database
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"

  couchDb:
    container_name: couch
    image: "couchdb:latest"
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: "admin"
      COUCHDB_PASSWORD: "password"
    volumes:
      - ./couchdb_data:/opt/couchdb/data
      - ./couchdb_config:/opt/couchdb/etc/local.d
      - ./couchdb_log:/opt/couchdb/var/log

  couchdb-init:
    image: curlimages/curl:latest
    depends_on:
      couchDb:
        condition: service_started
    environment:
      COUCHDB_USER: "admin"
      COUCHDB_PASSWORD: "password"
    entrypoint: >
        sh -c "
          echo 'Waiting for CouchDB to be ready...';
          until curl -s http://$${COUCHDB_USER}:$${COUCHDB_PASSWORD}@couch:5984/_all_dbs; do sleep 5; done;
          echo 'CouchDB is ready. Running initialization scripts...';
          curl -X PUT http://$${COUCHDB_USER}:$${COUCHDB_PASSWORD}@couch:5984/_users;
          curl -X PUT http://$${COUCHDB_USER}:$${COUCHDB_PASSWORD}@couch:5984/_replicator;
          curl -X PUT http://$${COUCHDB_USER}:$${COUCHDB_PASSWORD}@couch:5984/_global_changes;
        "
    restart: on-failure

  sdg-middleware:
    container_name: sdg-middleware
    depends_on:
      - database
    image: ghcr.io/engineering-research-and-development/synthetic-data-generator:middleware
    ports:
      - "8001:8001"
    environment:
      db_host: "database"
      db_name: "postgres"
      db_password: "postgres"
      db_username: "postgres"
      INIT_DB: True
      allowed_origins: '*'

  generator:
    container_name: sdg-generator
    depends_on:
      - sdg-middleware
      - couchDb
    image: ghcr.io/engineering-research-and-development/synthetic-data-generator:generator
    environment:
      couch_db: "http://admin:password@couchDb:5984"
    ports:
      - "8010:8010"

  frontend:
    container_name: sdg-frontend
    image: ghcr.io/engineering-research-and-development/synthetic-data-generator:frontend
    ports:
      - "5173:5173"
