name: Format with Black

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Prevents pushing directly to protected branches

      - name: Run Black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: './src/'

      - name: Commit and Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Apply Black formatting"
          branch: "black-auto-format"
          delete-branch: true
          title: "Auto-format code with Black"
          body: "This PR contains automatic formatting fixes applied by Black."
          labels: "auto-format, black"
          assignees: ${{ github.actor }}
