name: Synthetic Data Generator Integration Tests

on:
  push:
    branches: [ middleware ]
jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yaml"
          services: |
            sdg-middleware
            generator
            couchDb
          

      - name: Wait the container to be up and running
        run: |
          sleep 10

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r src/integration_test/test/requirements.txt

      - name: Run tests
        run: cd src/integration_test/test/ && pytest