name: Python Lint and Security generator

on:
  push:
    branches: [ "generator" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4

      - name: Set up Python environment ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/model_registry/test/requirements.txt
          pip install ruff bandit

      - name: Run Ruff
        run: |
          cd src/generator
          python -m ruff check ./server
          python -m ruff check ./ai_lib
          python -m ruff format --check ./server
          python -m ruff format --check ./ai_lib

      - name: Run bandit
        run: |
          cd src/generator          
          python -m bandit -r ./server
          python -m bandit -r ./ai_lib